__version__ = "0.0.6"
__date__ = "7 Jan 2021"
__link_source_code__ = "https://gitlab.ethz.ch/holukas/bico"
__link_releases__ = "https://gitlab.ethz.ch/holukas/bico/-/releases"
__link_wiki__ = "https://gitlab.ethz.ch/holukas/bico/-/wikis/home"
__license__ = "https://gitlab.ethz.ch/holukas/bico/-/blob/master/LICENSE"
