__version__ = "0.5.0"
__date__ = "23 Feb 2021"
__link_changelog__ = "https://gitlab.ethz.ch/holukas/bico/-/blob/master/CHANGELOG.md"
__link_source_code__ = "https://gitlab.ethz.ch/holukas/bico"
__link_releases__ = "https://gitlab.ethz.ch/holukas/bico/-/releases"
__link_wiki__ = "https://gitlab.ethz.ch/holukas/bico/-/wikis/home"
__license__ = "https://gitlab.ethz.ch/holukas/bico/-/blob/master/LICENSE"
